### ISSUE TITLE
Trying to register gtype 'WnckWindowState' as flags when in fact it is of type 'GEnum''

### ISSUE THREAD

**Issue by anubhavsinha** [ldtp/ldtp2#13]
[hpcuser@Order1 ~]$ python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 from ldtp import *

*\* (-c:338): WARNING **: Trying to register gtype 'WnckWindowState' as flags when in fact it is of type 'GEnum'

*\* (-c:338): WARNING **: Trying to register gtype 'WnckWindowActions' as flags when in fact it is of type 'GEnum'

*\* (-c:338): WARNING **: Trying to register gtype 'WnckWindowMoveResizeMask' as flags when in fact it is of type 'GEnum'

My environment is a centos 6.5 docker image. Could you please point me in the right direction where to look for fixing this issue?

**Comment by brownie313** [comment]
the rpms don't seem to exist anymore. Anyone knows where they've been moved to??
