### ISSUE TITLE
CentOs 6 works not well with ldtp

### ISSUE THREAD

**Issue by zhangqing2002aa** [ldtp/ldtp2#16]
I install LDTP on CentOS6,
There are errors:
[root@localhost Desktop]# python
Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ldtp import *

** (-c:51427): WARNING **: Trying to register gtype 'WnckWindowState' as flags when in fact it is of type 'GEnum'

** (-c:51427): WARNING **: Trying to register gtype 'WnckWindowActions' as flags when in fact it is of type 'GEnum'

** (-c:51427): WARNING **: Trying to register gtype 'WnckWindowMoveResizeMask' as flags when in fact it is of type 'GEnum'
>>> 
and can not work.How Can I do with it?

**Comment by nagappan** [comment]
This is not a bug, ignore the warnings
