### ISSUE TITLE
ldtp action 'click' does nothing on an element 'table cell header'

### ISSUE THREAD

**Issue by jstavel** [ldtp/ldtp2#29]
Hello,
am trying to click on a 'table cell header' in the application 'subscription-manager-gui'.

![snimek z 2016-10-12 13-39-32](https://cloud.githubusercontent.com/assets/2276410/19308929/6d2e8a3e-9082-11e6-9f68-d48d636ad1ef.png)

This code in ldtp does not work:
```python
selecttab("frmSubscriptionManager","ptl0", 'ptabAllAvailableSubscriptions')
click("frmSubscriptionManager","tchSubscription")
```

I have tried to perfom this action by dogtail library:
```python
#!/usr/bin/python
from dogtail import tree
submangui = [app for app in tree.root.applications()
                      if 'subscription-manager-gui' == app.name and app.children][0]
print submangui.child("All Subscriptions View", roleName="tree table")
   .child("Subscription", roleName="table column header")
   .doActionNamed('click')
```

I was trying to compare those codes. Both use an object of the same type at the end - atspi.Action.

I cannot find out differrences between ldtp code and dogtail code.
Maybe some configuration of AT-SPI layer. Or something else.

**Comment by nagappan** [comment]
Can you please provide me environment detail and the application ? I can try to reproduce

**Comment by jstavel** [comment]
Hello Nagappan,
I have finally found the source of my problem. The source was such that there are more than one 'table cell header' Subscription in the application.

It confused me that there is an action 'selecttab'. Each table is in another tab. So I saw just one table.

It works now with this code:
click("frmSubscriptionManager","tchSubscription1")

So the problem is solved.

**Comment by nagappan** [comment]
Good to know. Thanks
