### ISSUE TITLE
How is ldtp2 itself tested?

### ISSUE THREAD

**Issue by richelbilderbeek** [ldtp/ldtp2#33]
I wondered how `ldtp2` itself is tested. 

In case this is not done, or is done using manual scripts, then I volunteer to add automatic testing performed by Travis CI (free for FLOSS development).

**Comment by nagappan** [comment]
Only manual steps done, that will be a great support to the project

**Comment by richelbilderbeek** [comment]
I have prepared a first version of a Travis script, in which it installs LDTP (and passes). It is not completed yet, but it is a nice first step. Things to add are those manual procedures. I volunteer to add those.

If you'd accept the Pull Request, it is required that user `ldtp` activates a Travis CI account, at travis-ci.org . This is free for FLOSS and you can use your GitHub account.

Is that OK? If yes, I'll submit a PR.

**Comment by nagappan** [comment]
sure sounds good

**Comment by richelbilderbeek** [comment]
Added a PR [here](https://github.com/ldtp/ldtp2/pull/34)

**Comment by richelbilderbeek** [comment]
PR is accepted. Thanks!
