### ISSUE TITLE
What's the recommended Python version

### ISSUE THREAD

**Issue by brownie313** [ldtp/ldtp2#39]
Hi,

Is there a recommended python version to use with LDTP2?
I'm guessing it is 2.7?

**Comment by richelbilderbeek** [comment]
I know for sure that I don't know. I assume @nagappan knows.

**Comment by nagappan** [comment]
Yes I have tested with 2.7, I know other validated with 3.x

**Comment by brownie313** [comment]
Thanks a lot for your responses @richelbilderbeek and @nagappan.
