### ISSUE TITLE
LDTP in bugzilla.gnome.org will be gone soon, do you want its bugs here?

### ISSUE THREAD

**Issue by federicomenaquintero** [ldtp/ldtp2#46]
Please see https://lists.freedesktop.org/archives/ldtp-dev/2018-September/001302.html - bugzilla.gnome.org is shutting down REALLY SOON, as GNOME projects that were hosted on git.gnome.org have now moved to gitlab.gnome.org.

Do you want to move the LDTP bugs in bugzilla.gnome.org to github?  They will disappear otherwise.

**Comment by aklapper** [comment]
I've closed the remaining 17 open tickets in BZ with a comment to re-report in Github:
https://bugzilla.gnome.org//show_bug.cgi?id=347196#c2

If somebody wants to import these tickets, the full list is here: https://bugzilla.gnome.org//buglist.cgi?bug_id=683466,776853,676228,352220,324037,341226,580728,578123,574127,542909,578640,654856,323446,671210,343889,673938,347196 

Also see https://gitlab.gnome.org/Infrastructure/GitLab/issues/321

**Comment by aklapper** [comment]
(Also note that the bug reports likely won't entirely disappear but become read-only. Somehow. Details still to be sorted out.)

**Comment by federicomenaquintero** [comment]
Thanks; closing.

**Comment by waldyrious** [comment]
> If somebody wants to import these tickets

Are you talking about manually copy-pasting them to issues here, or using some automated migration process?

> Thanks; closing.

What does this closure mean that the bugs won't be imported, or that it's not relevant to migrate them if they will simply become read-only rather than disappear?

**Comment by aklapper** [comment]
> > If somebody wants to import these tickets
> 
> Are you talking about manually copy-pasting them to issues here, or using some automated migration process?

Either or. Up to LDTP maintainers what they plan to do.

> > Thanks; closing.
> 
> What does this closure mean that the bugs won't be imported, or that it's not relevant to migrate them if they will simply become read-only rather than disappear?

https://gitlab.gnome.org/Infrastructure/GitLab/issues/321#note_313984 asked to close the tickets in Bugzilla. That was a sufficient heads-up in my humble opinion, so this task has fulfilled its purpose and got closed.

**Comment by waldyrious** [comment]
> this task has fulfilled its purpose and got closed.

Fair enough. I'd consider this a reasonable place to track the actual importing of the bugs (seems on-topic), rather than opening a separate issue so that that task does not get lost track of, but that's just my 2¢; I don't have a strong opinion on this.
